name = '''Direct Plagiarism. Direct plagiarism is the word-for-word transcription of a section of someone else's work, without attribution and without quotation marks. ...
Self Plagiarism. ...
Mosaic Plagiarism. ...
Accidental Plagiarism'''
name = name.find('plagiarism')
print(name)
